name: Install Python Dependencies
description: Setup Python environment (venv)

runs:
  using: "composite"
  steps:
  
    - name: Checkout main repository
      uses: actions/checkout@v6

    - name: Clone repository (python-greetings)
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: greetings

    - name: Setup venv and install deps
      shell: cmd
      working-directory: greetings
      run: |
        echo Creating vertual environment
        python -m venv venv
        echo Installing dependencies
        venv\Scripts\python.exe -m pip install -r requirements.txt
