name: Deploy App
description: Deploying app with pm2

inputs:
  env:
    required: true
  port:
    required: true

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v6

    - name: Clone python-greetings repo
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: greetings

    - name: Setup virtual environment
      shell: cmd
      working-directory: greetings
      run: |
        python -m venv venv
        venv\Scripts\python.exe -m pip install -r requirements.txt

    - name: Stop existing app
      shell: cmd
      run: |
        pm2 delete greetings-app-${{ inputs.env }} & set "errorlevel=0"

    - name: Start app
      shell: cmd
      working-directory: greetings
      run: |
        echo Starting app on port ${{ inputs.port }}...
        pm2 start venv\Scripts\python.exe --name greetings-app-${{ inputs.env }} -- app.py --port ${{ inputs.port }}
