name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      name:
        type: string
        default: 'Hello!'
        description: 'Name Input'
        required: true

jobs:
  
  build:
    
    runs-on: self-hosted

    steps:

      - name: Run a one-line script
        run: echo Hello, world!
