name: Python Greetings Pipeline (Artemijs Plakitins 231RDB104)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: echo Installing dependencies...
      - name: Run install coposite action
        uses: ./.github/actions/install_dependencies
